# Generated by Django 4.0 on 2023-09-09 19:54

from django.db import migrations


def update_sites(apps, schema_editor):
    from django.contrib.sites.models import Site

    verify_domain_localhost = Site.objects.filter(domain='localhost:8000')
    if not verify_domain_localhost.exists():
        Site.objects.create(name='Local 01', domain='localhost:8000')


class Migration(migrations.Migration):
    dependencies = [
        ('bank', '0001_initial'),
        ]

    operations = [
        migrations.RunPython(update_sites),
        ]
